version: '3'
services:
  mongodb:
    container_name: udemymongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - .:/setup
    command: --auth
    environment:
      MONGODB_USER: "jhardison"
      MONGODB_DATABASE: "admin"
      MONGODB_PASS: "P@ssw0rd"